version: '3.7'

services:
  php:
    build: ./docker/php/
    container_name: nparser_php
    working_dir: /parser
    stdin_open: true
    volumes:
      - ./:/parser
      - /etc/letsencrypt/live/api.santehnika-online.nikparser.ru/:/etc/letsencrypt/live/api.santehnika-online.nikparser.ru/
    logging:
      driver: "local"
      options:
        max-size: 50m
        max-file: 3
    
  parser:
    build: ./docker/php/
    container_name: nparser_parser
    working_dir: /parser
    stdin_open: true
    volumes:
      - ./:/parser
    command: 
      - /bin/bash 
      - -c 
      - services/parser/start
    logging:
      driver: "local"
      options:
        max-size: 50m
        max-file: 3
    ports:
      - 8001:8001
    expose:
      - 8001

  mariadb:
    image: mariadb
    container_name: nparser_mariadb
    working_dir: /parser
    ports:
      - 3306:3306
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./mysql-data:/var/lib/mysql
      - .:/parser
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    logging:
      driver: "local"
      options:
        max-size: 50m
        max-file: 3

  loader:
    build: ./docker/loader/
    container_name: nparser_lodaer
    working_dir: /parser
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_ENABLE_TRACING=false
    ports:
     - "4444:4444"
    volumes:
     - /dev/shm:/dev/shm
     - .:/parser
    logging:
      driver: "local"
      options:
        max-size: 50m
        max-file: 3

  cron:
    build: ./docker/cron/
    container_name: nparser_cron
    working_dir: /parser
    stdin_open: true
    tty: true
    volumes:
      - .:/parser
    logging:
      driver: "local"
      options:
        max-size: 50m
        max-file: 3
   #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nparser_vseinstruments_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/parser
      -  /etc/letsencrypt/:/etc/letsencrypt/
      - ./docker/nginx/vhosts.conf:/etc/nginx/conf.d/default.conf:delegated
    logging:
      driver: "local"
      options:
        max-size: 50m
        max-file: 3

networks:
  default:
    name: nparser_network
